### ISSUE TITLE
부트스트랩에서 제공하는 클래스를 override하지 않기

### ISSUE THREAD

**Issue by selenehyun** [taesung1993/shopping#1]
https://github.com/taesung1993/shopping/blob/b5499167c32c33b08c0834a46da8d4abc2d26b41/css/styles.css#L14-L17

지금 이 코드는 부트스트랩이 제공하는 클래스와 동일한 이름을 가지고 있습니다.
이렇게 스타일을 관리하게 되면 나중에 `.container`를 다른곳에 이용하더라도 내가 알고있던 부트스트랩의 스타일이 아닌, 다른 이상한 스타일을 마주하게 될수 있습니다 :)

고로 어떤 라이브러리와도 이름이 겹치지 않도록 `.my-container`, `.page-container` 같이 특별한 이름을 사용해보세요 🙂

**Comment by selenehyun** [comment]
여기서 언급하지 않은 col-* 같은 다른 클래스도 마찬가지입니다!

**Comment by taesung1993** [comment]
정말 좋은 리뷰 감사드립니다. 😀
css 파일을 만들어 추가적으로 스타일을 주려면 
기존 부트스트랩 클래스 이름과 겹치지 않게 클래스 이름을 새로 주시라는 
말씀이신가요 :) ?
수업시간에 튜터님이 말씀해주셨었는데 만들고 있는 상황에서는
그것을 인지하지 못했네요!
다음 코드 작성시에는 이 점을 좀 더 유의해서 작성해야겠네요 :)
감사합니다.
